name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Build iOS Action
      uses: sparkfabrik/ios-build-action@v2.3.2
      with:
          upload-to-testflight: false
          increment-build-number: true
          build-pods: false
          pods-path: "ios/Podfile"
          configuration: Release
          export-method: development
          workspace-path: ""
          project-path: "AniAnglia.xcodeproj"
          scheme: MyScheme
          output-path: build-${{ github.sha }}.ipa
          team-id: ${{ secrets.TEAM_ID }}
          team-name: ${{ secrets.TEAM_NAME }}
          browserstack-upload: false
          fastlane-env: stage
          ios-app-id: org.toilettrauma.AniAnglia
            
